import { Calculator, CalculatorCategory } from '@/types'

export type RealLifeCategory = 
  | 'finance' 
  | 'everyday' 
  | 'health' 
  | 'home' 
  | 'auto' 
  | 'education' 
  | 'time'

export const realLifeCategoryLabels: Record<RealLifeCategory, { ru: string; en: string }> = {
  finance: { ru: 'Финансы', en: 'Finance' },
  everyday: { ru: 'Повседневные', en: 'Everyday Life' },
  health: { ru: 'Здоровье', en: 'Health' },
  home: { ru: 'Жильё', en: 'Home & Real Estate' },
  auto: { ru: 'Автомобиль', en: 'Auto & Transport' },
  education: { ru: 'Образование', en: 'Education' },
  time: { ru: 'Время и дата', en: 'Time & Date' },
}

export const realLifeCalculators: Calculator[] = [
  // === FINANCE (12) ===
  {
    id: 'loan',
    slug: 'loan-calculator',
    name: 'Кредитный калькулятор',
    description: 'Расчёт ежемесячного платежа, переплаты и графика платежей по кредиту',
    category: 'finance',
    icon: 'CreditCard',
    keywords: ['кредит', 'ипотека', 'платёж', 'процент', 'credit', 'loan', 'mortgage'],
    difficulty: 'beginner',
    tags: ['кредит', 'ипотека', 'финансы'],
  },
  {
    id: 'deposit',
    slug: 'deposit-calculator',
    name: 'Депозитный калькулятор',
    description: 'Расчёт дохода по вкладу с учётом капитализации процентов',
    category: 'finance',
    icon: 'PiggyBank',
    keywords: ['депозит', 'вклад', 'процент', 'капитализация', 'deposit', 'interest'],
    difficulty: 'beginner',
    tags: ['депозит', 'вклад', 'инвестиции'],
  },
  {
    id: 'mortgage',
    slug: 'mortgage-calculator',
    name: 'Ипотечный калькулятор',
    description: 'Расчёт ипотеки с первоначальным взносом и досрочным погашением',
    category: 'finance',
    icon: 'Home',
    keywords: ['ипотека', 'квартира', 'жильё', 'mortgage', 'apartment'],
    difficulty: 'beginner',
    tags: ['ипотека', 'квартира', 'жильё'],
  },
  {
    id: 'investment',
    slug: 'investment-calculator',
    name: 'Инвестиционный калькулятор',
    description: 'Расчёт доходности инвестиций с учётом сложных процентов',
    category: 'finance',
    icon: 'TrendingUp',
    keywords: ['инвестиции', 'доходность', 'roi', 'сложный процент', 'investment'],
    difficulty: 'intermediate',
    tags: ['инвестиции', 'доходность', 'прибыль'],
  },
  {
    id: 'vat',
    slug: 'vat-calculator',
    name: 'Калькулятор НДС',
    description: 'Выделение или начисление НДС из суммы',
    category: 'finance',
    icon: 'Receipt',
    keywords: ['ндс', 'налог', 'vat', 'tax'],
    difficulty: 'beginner',
    tags: ['ндс', 'налог', 'бухгалтерия'],
  },
  {
    id: 'salary-net',
    slug: 'salary-net-calculator',
    name: 'Зарплата: на руки / до налогов',
    description: 'Перевод зарплаты "на руки" в "до налогов" и наоборот',
    category: 'finance',
    icon: 'Wallet',
    keywords: ['зарплата', 'net', 'gross', 'налог', 'salary', 'вычет'],
    difficulty: 'beginner',
    tags: ['зарплата', 'налог', 'доход'],
  },
  {
    id: 'currency',
    slug: 'currency-converter',
    name: 'Конвертер валют',
    description: 'Конвертация между популярными валютами по курсу ЦБ',
    category: 'finance',
    icon: 'RefreshCw',
    keywords: ['валюта', 'конвертер', 'курс', 'доллар', 'евро', 'currency', 'exchange'],
    difficulty: 'beginner',
    tags: ['валюта', 'конвертация', 'курс'],
  },
  {
    id: 'inflation',
    slug: 'inflation-calculator',
    name: 'Калькулятор инфляции',
    description: 'Учёт инфляции: сколько будут стоить деньги через N лет',
    category: 'finance',
    icon: 'DollarSign',
    keywords: ['инфляция', 'покупательная', 'inflation', 'деньги'],
    difficulty: 'intermediate',
    tags: ['инфляция', 'деньги', 'стоимость'],
  },
  {
    id: 'tip',
    slug: 'tip-calculator',
    name: 'Калькулятор чаевых',
    description: 'Расчёт чаевых в ресторане с учётом количества человек',
    category: 'finance',
    icon: 'Coffee',
    keywords: ['чаевые', 'ресторан', 'tip', 'gratuity'],
    difficulty: 'beginner',
    tags: ['чаевые', 'ресторан', 'сервис'],
  },
  {
    id: 'profit',
    slug: 'profit-margin-calculator',
    name: 'Калькулятор наценки и прибыли',
    description: 'Расчёт наценки, маржи и себестоимости',
    category: 'finance',
    icon: 'BarChart',
    keywords: ['наценка', 'маржа', 'прибыль', 'себестоимость', 'margin', 'profit'],
    difficulty: 'intermediate',
    tags: ['бизнес', 'прибыль', 'торговля'],
  },
  {
    id: 'discount',
    slug: 'discount-calculator',
    name: 'Калькулятор скидок',
    description: 'Расчёт итоговой цены с несколькими скидками и купонами',
    category: 'finance',
    icon: 'Tag',
    keywords: ['скидка', 'купон', 'акция', 'discount', 'sale'],
    difficulty: 'beginner',
    tags: ['скидка', 'покупки', 'экономия'],
  },

  // === EVERYDAY LIFE (15) ===
  {
    id: 'fuel',
    slug: 'fuel-consumption-calculator',
    name: 'Расход топлива',
    description: 'Расчёт среднего расхода топлива и стоимости поездки',
    category: 'everyday',
    icon: 'Fuel',
    keywords: ['топливо', 'бензин', 'расход', 'fuel', 'gas', 'mileage'],
    difficulty: 'beginner',
    tags: ['топливо', 'авто', 'поездка'],
  },
  {
    id: 'trip-cost',
    slug: 'trip-cost-calculator',
    name: 'Стоимость поездки',
    description: 'Расчёт полной стоимости путешествия: топливо, отели, еда',
    category: 'everyday',
    icon: 'MapPin',
    keywords: ['поездка', 'путешествие', 'авто', 'trip', 'travel'],
    difficulty: 'beginner',
    tags: ['поездка', 'путешествие', 'бюджет'],
  },
  {
    id: 'electricity',
    slug: 'electricity-bill-calculator',
    name: 'Счёт за электричество',
    description: 'Расчёт стоимости электроэнергии по тарифу и показаниям',
    category: 'everyday',
    icon: 'Zap',
    keywords: ['электричество', 'счёт', 'тариф', 'квт', 'electricity', 'utility'],
    difficulty: 'beginner',
    tags: ['электричество', 'счёт', 'коммуналка'],
  },
  {
    id: 'water',
    slug: 'water-bill-calculator',
    name: 'Счёт за воду',
    description: 'Расчёт стоимости воды по показаниям счётчика',
    category: 'everyday',
    icon: 'Droplet',
    keywords: ['вода', 'счётчик', 'тариф', 'water', 'utility'],
    difficulty: 'beginner',
    tags: ['вода', 'коммуналка', 'счётчик'],
  },
  {
    id: 'heating',
    slug: 'heating-cost-calculator',
    name: 'Стоимость отопления',
    description: 'Расчёт платы за отопление по площади квартиры',
    category: 'everyday',
    icon: 'Flame',
    keywords: ['отопление', 'квартира', 'тариф', 'heating', 'utility'],
    difficulty: 'beginner',
    tags: ['отопление', 'квартира', 'коммуналка'],
  },
  {
    id: 'price-per-unit',
    slug: 'price-per-unit-calculator',
    name: 'Цена за единицу',
    description: 'Сравнение цен: выгоднее ли большую упаковку?',
    category: 'everyday',
    icon: 'Scale',
    keywords: ['цена', 'единица', 'кг', 'литр', 'price', 'unit', 'кг'],
    difficulty: 'beginner',
    tags: ['цена', 'сравнение', 'выгода'],
  },
  {
    id: 'split-bill',
    slug: 'split-bill-calculator',
    name: 'Разделение счёта',
    description: 'Разделение счёта в ресторате на нескольких человек',
    category: 'everyday',
    icon: 'Users',
    keywords: ['счёт', 'делить', 'ресторан', 'bill', 'split', 'check'],
    difficulty: 'beginner',
    tags: ['ресторан', 'делить', 'компания'],
  },
  {
    id: 'moving',
    slug: 'moving-cost-calculator',
    name: 'Стоимость переезда',
    description: 'Расчёт расходов на переезд: транспорт, грузчики, упаковка',
    category: 'everyday',
    icon: 'Truck',
    keywords: ['переезд', 'грузчики', 'транспорт', 'moving', 'relocation'],
    difficulty: 'intermediate',
    tags: ['переезд', 'груз', 'транспорт'],
  },
  {
    id: 'parking',
    slug: 'parking-fee-calculator',
    name: 'Стоимость парковки',
    description: 'Расчёт стоимости парковки по часам или дням',
    category: 'everyday',
    icon: 'Car',
    keywords: ['парковка', 'стоянка', 'parking', 'fee'],
    difficulty: 'beginner',
    tags: ['парковка', 'стоянка', 'авто'],
  },
  {
    id: 'phone-plan',
    slug: 'phone-plan-calculator',
    name: 'Сравнение тарифов',
    description: 'Сравнение мобильных тарифов по минутам и трафику',
    category: 'everyday',
    icon: 'Smartphone',
    keywords: ['тариф', 'мобильный', 'минуты', 'трафик', 'phone', 'tariff'],
    difficulty: 'beginner',
    tags: ['тариф', 'связь', 'мобильный'],
  },
  {
    id: 'rent-vs-buy',
    slug: 'rent-vs-buy-calculator',
    name: 'Аренда vs Покупка',
    description: 'Сравнение: выгоднее арендовать или купить жильё?',
    category: 'everyday',
    icon: 'Building',
    keywords: ['аренда', 'покупка', 'квартира', 'rent', 'buy', 'apartment'],
    difficulty: 'intermediate',
    tags: ['аренда', 'покупка', 'жильё'],
  },
  {
    id: 'pet-cost',
    slug: 'pet-cost-calculator',
    name: 'Стоимость питомца',
    description: 'Расчёт годовых расходов на содержание домашнего животного',
    category: 'everyday',
    icon: 'Heart',
    keywords: ['питомец', 'кошка', 'собака', 'корм', 'pet', 'cat', 'dog'],
    difficulty: 'beginner',
    tags: ['питомец', 'животное', 'корм'],
  },
  {
    id: 'warranty',
    slug: 'warranty-value-calculator',
    name: 'Выкупная стоимость',
    description: 'Расчёт выкупной стоимости товара по гарантии',
    category: 'everyday',
    icon: 'Shield',
    keywords: ['гарантия', 'выкуп', 'товар', 'warranty', 'buyback'],
    difficulty: 'beginner',
    tags: ['гарантия', 'возврат', 'товар'],
  },

  // === HEALTH (8) ===
  {
    id: 'bmi',
    slug: 'bmi-calculator',
    name: 'Индекс массы тела',
    description: 'Расчёт ИМТ (BMI) с интерпретацией результата',
    category: 'health',
    icon: 'User',
    keywords: ['имт', 'bmi', 'вес', 'рост', 'индекс массы'],
    difficulty: 'beginner',
    tags: ['здоровье', 'вес', 'питание'],
  },
  {
    id: 'calories',
    slug: 'calorie-calculator',
    name: 'Калькулятор калорий',
    description: 'Расчёт суточной нормы калорий с учётом активности',
    category: 'health',
    icon: 'Flame',
    keywords: ['калории', 'ккал', 'диета', 'calories', 'diet', 'nutrition'],
    difficulty: 'intermediate',
    tags: ['калории', 'диета', 'питание'],
  },
  {
    id: 'water-intake',
    slug: 'water-intake-calculator',
    name: 'Норма воды',
    description: 'Расчёт рекомендуемого потребления воды в день',
    category: 'health',
    icon: 'Droplets',
    keywords: ['вода', 'питьё', 'гидратация', 'water', 'hydration'],
    difficulty: 'beginner',
    tags: ['вода', 'здоровье', 'гидратация'],
  },
  {
    id: 'sleep',
    slug: 'sleep-calculator',
    name: 'Калькулятор сна',
    description: 'Расчёт оптиального времени сна и пробуждения',
    category: 'health',
    icon: 'Moon',
    keywords: ['сон', 'отдых', 'кровать', 'sleep', 'rest'],
    difficulty: 'beginner',
    tags: ['сон', 'отдых', 'здоровье'],
  },
  {
    id: 'heart-rate',
    slug: 'heart-rate-calculator',
    name: 'Зоны пульса',
    description: 'Расчёт целевых зон пульса для тренировок',
    category: 'health',
    icon: 'Activity',
    keywords: ['пульс', 'чсс', 'тренировка', 'heart rate', 'pulse'],
    difficulty: 'beginner',
    tags: ['пульс', 'тренировка', 'спорт'],
  },
  {
    id: 'ideal-weight',
    slug: 'ideal-weight-calculator',
    name: 'Идеальный вес',
    description: 'Расчёт идеального веса по нескольким формулам',
    category: 'health',
    icon: 'Scale',
    keywords: ['вес', 'идеальный', 'норма', 'ideal weight', 'healthy'],
    difficulty: 'beginner',
    tags: ['вес', 'здоровье', 'норма'],
  },

  // === HOME & REAL ESTATE (8) ===
  {
    id: 'paint',
    slug: 'paint-calculator',
    name: 'Калькулятор краски',
    description: 'Расчёт количества краски для покраски комнаты',
    category: 'home',
    icon: 'Paintbrush',
    keywords: ['краска', 'покраска', 'комната', 'paint', 'room'],
    difficulty: 'beginner',
    tags: ['краска', 'ремонт', 'комната'],
  },
  {
    id: 'tiles',
    slug: 'tiles-calculator',
    name: 'Калькулятор плитки',
    description: 'Расчёт количества плитки для пола или стен',
    category: 'home',
    icon: 'Grid',
    keywords: ['плитка', 'пол', 'стена', 'tile', 'floor'],
    difficulty: 'beginner',
    tags: ['плитка', 'ремонт', 'пол'],
  },
  {
    id: 'flooring',
    slug: 'flooring-calculator',
    name: 'Калькулятор напольных покрытий',
    description: 'Расчёт ламината, паркета или линолеума',
    category: 'home',
    icon: 'Layers',
    keywords: ['ламинат', 'паркет', 'пол', 'flooring', 'laminate'],
    difficulty: 'beginner',
    tags: ['пол', 'ламинат', 'ремонт'],
  },
  {
    id: 'hvac',
    slug: 'hvac-calculator',
    name: 'Мощность кондиционера',
    description: 'Расчёт необходимой мощности кондиционера для комнаты',
    category: 'home',
    icon: 'Thermometer',
    keywords: ['кондиционер', 'мощность', 'бтиу', 'ac', 'cooling'],
    difficulty: 'intermediate',
    tags: ['кондиционер', 'мощность', 'климат'],
  },
  {
    id: 'home-affordability',
    slug: 'home-affordability-calculator',
    name: 'Доступность жилья',
    description: 'Оценка: на какую сумму жилья вы можете рассчитывать',
    category: 'home',
    icon: 'Building',
    keywords: ['жильё', 'квартира', 'ипотека', 'доступность', 'afford'],
    difficulty: 'intermediate',
    tags: ['жильё', 'ипотека', 'бюджет'],
  },
  {
    id: 'property-tax',
    slug: 'property-tax-calculator',
    name: 'Налог на недвижимость',
    description: 'Расчёт налога на квартиру или дом',
    category: 'home',
    icon: 'Home',
    keywords: ['налог', 'недвижимость', 'квартира', 'property tax'],
    difficulty: 'intermediate',
    tags: ['налог', 'недвижимость', 'квартира'],
  },
  {
    id: 'mortgage-affordability',
    slug: 'mortgage-affordability-calculator',
    name: 'Максимальная ипотека',
    description: 'Расчёт максимальной суммы ипотеки по доходу',
    category: 'home',
    icon: 'Calculator',
    keywords: ['ипотека', 'доход', 'максимум', 'mortgage', 'eligibility'],
    difficulty: 'intermediate',
    tags: ['ипотека', 'доход', 'кредит'],
  },
  {
    id: 'room-area',
    slug: 'room-area-calculator',
    name: 'Площадь комнаты',
    description: 'Расчёт площади стен, пола и потолка комнаты',
    category: 'home',
    icon: 'Maximize2',
    keywords: ['площадь', 'стены', 'пол', 'потолок', 'area', 'room'],
    difficulty: 'beginner',
    tags: ['площадь', 'ремонт', 'комната'],
  },

  // === AUTO & TRANSPORT (5) ===
  {
    id: 'car-loan',
    slug: 'car-loan-calculator',
    name: 'Автокредит',
    description: 'Расчёт платежа по кредиту на автомобиль',
    category: 'auto',
    icon: 'Car',
    keywords: ['автокредит', 'машина', 'кредит', 'car loan', 'auto'],
    difficulty: 'beginner',
    tags: ['авто', 'кредит', 'машина'],
  },
  {
    id: 'fuel-economy',
    slug: 'fuel-economy-calculator',
    name: 'Расход топлива (л/100км)',
    description: 'Точный расчёт расхода топлива на 100 км',
    category: 'auto',
    icon: 'Gauge',
    keywords: ['расход', 'топливо', 'л/100км', 'fuel economy', 'mpg'],
    difficulty: 'beginner',
    tags: ['расход', 'топливо', 'авто'],
  },
  {
    id: 'ev-charging',
    slug: 'ev-charging-calculator',
    name: 'Зарядка электромобиля',
    description: 'Расчёт стоимости зарядки электромобиля',
    category: 'auto',
    icon: 'Plug',
    keywords: ['электромобиль', 'зарядка', 'ev', 'charging'],
    difficulty: 'beginner',
    tags: ['электромобиль', 'зарядка', 'электричество'],
  },
  {
    id: 'tire-size',
    slug: 'tire-size-calculator',
    name: 'Размер шин',
    description: 'Расчёт диаметра и окружности колеса по размерам шины',
    category: 'auto',
    icon: 'Circle',
    keywords: ['шины', 'колесо', 'диаметр', 'tire', 'wheel'],
    difficulty: 'beginner',
    tags: ['шины', 'колесо', 'авто'],
  },
  {
    id: 'maintenance',
    slug: 'car-maintenance-calculator',
    name: 'ТО автомобиля',
    description: 'Расчёт ориентировочной стоимости ТО и ремонта',
    category: 'auto',
    icon: 'Wrench',
    keywords: ['то', 'ремонт', 'авто', 'maintenance', 'service'],
    difficulty: 'beginner',
    tags: ['то', 'ремонт', 'авто'],
  },

  // === EDUCATION (5) ===
  {
    id: 'grade',
    slug: 'grade-calculator',
    name: 'Средний балл',
    description: 'Расчёт среднего балла оценок за семестр или год',
    category: 'education',
    icon: 'Award',
    keywords: ['оценка', 'балл', 'средний', 'grade', 'gpa'],
    difficulty: 'beginner',
    tags: ['оценки', 'учеба', 'балл'],
  },
  {
    id: 'student-loan',
    slug: 'student-loan-calculator',
    name: 'Студенческий кредит',
    description: 'Расчёт выплат по студенческому кредиту',
    category: 'education',
    icon: 'BookOpen',
    keywords: ['студент', 'кредит', 'учеба', 'student loan'],
    difficulty: 'intermediate',
    tags: ['студент', 'кредит', 'учеба'],
  },
  {
    id: 'study-time',
    slug: 'study-time-calculator',
    name: 'Планировщик учёбы',
    description: 'Расчёт времени на изучение предмета для экзамена',
    category: 'education',
    icon: 'Clock',
    keywords: ['учеба', 'время', 'экзамен', 'study', 'exam'],
    difficulty: 'beginner',
    tags: ['учеба', 'время', 'экзамен'],
  },
  {
    id: 'exam-score',
    slug: 'exam-score-calculator',
    name: 'Проходной балл',
    description: 'Расчёт: сколько нужно баллов на экзамене',
    category: 'education',
    icon: 'Target',
    keywords: ['экзамен', 'балл', 'проходной', 'exam', 'score'],
    difficulty: 'beginner',
    tags: ['экзамен', 'балл', 'поступление'],
  },

  // === TIME & DATE (3) ===
  {
    id: 'age',
    slug: 'age-calculator',
    name: 'Калькулятор возраста',
    description: 'Точный возраст в годах, месяцах и днях',
    category: 'time',
    icon: 'CalendarDays',
    keywords: ['возраст', 'день рождения', 'age', 'birthday'],
    difficulty: 'beginner',
    tags: ['возраст', 'дата', 'др'],
  },
  {
    id: 'date-diff',
    slug: 'date-difference-calculator',
    name: 'Разница между датами',
    description: 'Количество дней, недель, месяцев между двумя датами',
    category: 'time',
    icon: 'CalendarRange',
    keywords: ['дата', 'дней', 'разница', 'date', 'days', 'difference'],
    difficulty: 'beginner',
    tags: ['дата', 'дней', 'период'],
  },
  {
    id: 'timezone',
    slug: 'timezone-converter',
    name: 'Конвертер часовых поясов',
    description: 'Перевод времени между городами и часовыми поясами',
    category: 'time',
    icon: 'Globe',
    keywords: ['время', 'пояс', 'город', 'timezone', 'time zone'],
    difficulty: 'beginner',
    tags: ['время', 'пояс', 'город'],
  },
]

export const getRealLifeCalculatorsByCategory = (category: RealLifeCategory): Calculator[] => {
  return realLifeCalculators.filter((calc) => calc.category === category)
}

export const getRealLifeCalculatorBySlug = (slug: string): Calculator | undefined => {
  return realLifeCalculators.find((calc) => calc.slug === slug)
}
